export const FETCH_VOLUNTEER_SEARCH_REQUEST = "FETCH_VOLUNTEER_SEARCH_REQUEST";
export const FETCH_VOLUNTEER_SEARCH_SUCCESS = "FETCH_VOLUNTEER_SEARCH_SUCCESS";
export const FETCH_VOLUNTEER_SEARCH_FAILURE = "FETCH_VOLUNTEER_SEARCH_FAILURE";
