export const FETCH_BLOOD_BANK_SEARCH_REQUEST = "FETCH_BLOOD_BANK_SEARCH_REQUEST";
export const FETCH_BLOOD_BANK_SEARCH_SUCCESS = "FETCH_BLOOD_BANK_SEARCH_SUCCESS";
export const FETCH_BLOOD_BANK_SEARCH_FAILURE = "FETCH_BLOOD_BANK_SEARCH_FAILURE";
