export const FETCH_BLOOD_BANK_REQUEST = "FETCH_BLOOD_BANK_REQUEST";
export const FETCH_BLOOD_BANK_SUCCESS = "FETCH_BLOOD_BANK_SUCCESS";
export const FETCH_BLOOD_BANK_FAILURE = "FETCH_BLOOD_BANK_FAILURE";
